global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: /metrics

  - job_name: 'rooms'
    static_configs:
      - targets: ['rooms:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'reservations'
    static_configs:
      - targets: ['reservations:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'users'
    static_configs:
      - targets: ['users:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'payments'
    static_configs:
      - targets: ['payments:3004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'notifications'
    static_configs:
      - targets: ['notifications:3005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    metrics_path: '/metrics'
    scrape_interval: 30s 