apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: easy-hotel
data:
  # Database URLs
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5433"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "easy_hotel_users"
  POSTGRES_DB_ROOMS: "easy_hotel_rooms"
  POSTGRES_DB_RESERVATIONS: "easy_hotel_reservations"
  POSTGRES_DB_PAYMENTS: "easy_hotel_payments"
  POSTGRES_DB_NOTIFICATIONS: "easy_hotel_notifications"
  
  # Redis
  REDIS_URL: "redis://redis-service:6379"
  
  # MongoDB
  MONGODB_URL: "mongodb://mongodb-service:27017/easy_hotel"
  
  # URLs dos serviços
  ROOMS_URL: "http://rooms-service:3002"
  RESERVATIONS_URL: "http://reservations-service:3001"
  USERS_URL: "http://users-service:3003"
  PAYMENTS_URL: "http://payments-service:3004"
  NOTIFICATIONS_URL: "http://notifications-service:3005"
  KONG_URL: "http://kong:8001"
  
  # Kafka Event Streaming
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_TOPIC_RESERVATIONS: "hotel.reservations"
  KAFKA_TOPIC_ROOMS: "hotel.rooms"
  KAFKA_TOPIC_USERS: "hotel.users"
  KAFKA_TOPIC_PAYMENTS: "hotel.payments"
  KAFKA_TOPIC_NOTIFICATIONS: "hotel.notifications"
  KAFKA_TOPIC_SYSTEM: "hotel.system"
  
  # JWT
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
  
  # Environment
  NODE_ENV: "development"
  RAILS_ENV: "development" 