apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: easy-hotel
  labels:
    app: notifications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      initContainers:
      - name: wait-for-mongodb
        image: mongo:6
        command: ['sh', '-c', 'until mongosh --host mongodb-service --port 27017 --eval "db.adminCommand(\"ping\")" --quiet; do echo waiting for mongodb; sleep 2; done;']
      containers:
      - name: notifications
        image: easy-hotel-notifications:latest
        imagePullPolicy: Never  # Para desenvolvimento local
        ports:
        - containerPort: 3005
        env:
        - name: PORT
          value: "3005"
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_URL
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: KAFKA_BROKERS
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWILIO_ACCOUNT_SID
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWILIO_AUTH_TOKEN
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SMTP_USERNAME
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SMTP_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: easy-hotel
spec:
  selector:
    app: notifications
  ports:
  - port: 3005
    targetPort: 3005
  type: ClusterIP 