apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservations
  namespace: easy-hotel
  labels:
    app: reservations
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        command: ['sh', '-c', 'until pg_isready -h postgres-service -p 5433; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: reservations
        image: easy-hotel-reservations:latest
        imagePullPolicy: Never  # Para desenvolvimento local
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB_RESERVATIONS
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres-service:5433/easy_hotel_reservations?schema=public"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: reservations-service
  namespace: easy-hotel
spec:
  selector:
    app: reservations
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP 