apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms
  namespace: easy-hotel
  labels:
    app: rooms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rooms
  template:
    metadata:
      labels:
        app: rooms
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres:15
        command: ['sh', '-c', 'until pg_isready -h postgres-service -p 5433; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: rooms
        image: easy-hotel-rooms:latest
        imagePullPolicy: Never  # Para desenvolvimento local
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: RAILS_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RAILS_ENV
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB_ROOMS
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres-service:5433/easy_hotel_rooms?schema=public"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: rooms-service
  namespace: easy-hotel
spec:
  selector:
    app: rooms
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP 